//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using KhMedium.Models;

namespace KhMedium.Models

{
    using System;
    using System.Collections.Generic;
    
    public class ArticleModel
    {
        public ArticleModel()
        {
            this.ArticleTags = new List<ArticleTagModel>();
            this.Bookmarks = new List<BookmarkModel>();
            this.Claps = new List<ClapModel>();
            this.Comments = new List<CommentModel>();
            this.Shares = new List<ShareModel>();
        }
    
        public string Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string TopicId { get; set; }
        public string AuthorId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        public virtual AuthorModel Author { get; set; }
        public virtual TopicModel Topic { get; set; }
        public virtual ICollection<ArticleTagModel> ArticleTags { get; set; }
        public virtual ICollection<BookmarkModel> Bookmarks { get; set; }
        public virtual ICollection<ClapModel> Claps { get; set; }
        public virtual ICollection<CommentModel> Comments { get; set; }
        public virtual ICollection<ShareModel> Shares { get; set; }
    }
}
