//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using KhMedium.Models;

namespace KhMedium.Model

{
    using System;
    using System.Collections.Generic;
    
    public class Article
    {
        public Article()
        {
            this.ArticleTags = new List<ArticleTag>();
            this.Bookmarks = new List<Bookmark>();
            this.Claps = new List<Clap>();
            this.Comments = new List<Comment>();
            this.Shares = new List<Share>();
        }
    
        public string Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string TopicId { get; set; }
        public string AuthorId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Topic Topic { get; set; }
        public virtual ICollection<ArticleTag> ArticleTags { get; set; }
        public virtual ICollection<Bookmark> Bookmarks { get; set; }
        public virtual ICollection<Clap> Claps { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Share> Shares { get; set; }
    }
}
