//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using KhMedium.Models;

namespace KhMedium.Model
{
    using System;
    using System.Collections.Generic;
    
    public  class Author
    {
        public Author()
        {
            this.Articles = new HashSet<Article>();
            this.Followers = new HashSet<Follower>();
            this.Followings = new HashSet<Following>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string ProfilePicture { get; set; }
        public string PublicationId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        public virtual ICollection<Article> Articles { get; set; }
        public virtual Publication Publication { get; set; }
        public virtual ICollection<Follower> Followers { get; set; }
        public virtual ICollection<Following> Followings { get; set; }
    }
}
