//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using KhMedium.Entities;

namespace KhMedium.Models
{
    using System;
    using System.Collections.Generic;
    
    public  class FollowerModel
    {
        public string Id { get; set; }
        public string FollowerId { get; set; }
        public string UserId { get; set; }
        public string AuthorId { get; set; }
        public string PublicationId { get; set; }
        public string TopicId { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AuthorModel Author { get; set; }
        public virtual PublicationModel Publication { get; set; }
        public virtual TopicModel Topic { get; set; }
    }
}
