//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using KhMedium.Model;

namespace KhMedium.Models
{
    using System;
    using System.Collections.Generic;
    
    public class Publication
    {
        public Publication()
        {
            this.Authors = new List<Author>();
            this.Followers = new List<Follower>();
            this.Followings = new List<Following>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string About { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        public virtual ICollection<Author> Authors { get; set; }
        public virtual ICollection<Follower> Followers { get; set; }
        public virtual ICollection<Following> Followings { get; set; }
    }
}
