//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using KhMedium.Model;

namespace KhMedium.Models
{
    using System;
    using System.Collections.Generic;
    
    public  class Topic
    {
        public Topic()
        {
            this.Articles = new HashSet<Article>();
            this.Followers = new HashSet<Follower>();
            this.Followings = new HashSet<Following>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string CategoryId { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual ICollection<Article> Articles { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<Follower> Followers { get; set; }
        public virtual ICollection<Following> Followings { get; set; }
    }
}
