//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KhMedium.Models
{
    using System;
    using System.Collections.Generic;
    
    public  class TopicModel
    {
        public TopicModel()
        {
            this.Articles = new HashSet<ArticleModel>();
            this.Followers = new HashSet<FollowerModel>();
            this.Followings = new HashSet<FollowingModel>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string CategoryId { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual ICollection<ArticleModel> Articles { get; set; }
        public virtual CategoryModel Category { get; set; }
        public virtual ICollection<FollowerModel> Followers { get; set; }
        public virtual ICollection<FollowingModel> Followings { get; set; }
    }
}
