//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhMedium.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clap
    {
        public string Id { get; set; }
        public int Count { get; set; }
        public string ArticleId { get; set; }
        public string UserId { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
